server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:8086

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/v1/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**


# okta config for api gateway

okta:
  oauth2:
    issuer: https://dev-91659780.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9f5e7uwbAHdLhQ5d7
    client-secret: MC3--nP2zhe__vCMxubuGKMvc7GqD-lz6RQiYDmp
    scopes: openid, profile, email, offline_access
