server:
  port: 8080

spring:
  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8086

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-91659780.okta.com/oauth2/default

      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa9f5e7uwbAHdLhQ5d7
            client-secret: MC3--nP2zhe__vCMxubuGKMvc7GqD-lz6RQiYDmp

        provider:
          okta:
            issuer-uri: https://dev-91659780.okta.com/oauth2/default

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_rating
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, beans

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 3s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s


okta:
  oauth2:
    issuer: https://dev-91659780.okta.com/oauth2/default
    audience: api://default


